### ISSUE TITLE
rm in setup.sh fails if files not present

### ISSUE THREAD

**Issue by spaceboy89** [domWalters/aarch64-crosscompiler-build-scripts#1]
setup.sh fails when run for the first time as rm complains that files don't exist

add -f to all rm to suppress the error

**Comment by domWalters** [comment]
I think a better solution is probably just to remove the "set -euo pipefail" at the top. I used that for the run script to make sure it crashes if any part of the install fails, but for setup it isn't necessary. Also I believe some of those set flags are deprecated and I shouldn't really be using them in the first place.
